from app.postgres_schema import POSTGRES_SCHEMA_SQL, assert_postgres_schema_is_not_sqlite_specific


def test_postgres_schema_avoids_sqlite_specific_tokens():
    assert_postgres_schema_is_not_sqlite_specific()
    lowered = POSTGRES_SCHEMA_SQL.lower()

    assert "autoincrement" not in lowered
    assert "sqlite_master" not in lowered
    assert "pragma" not in lowered
    assert "generated by default as identity" in lowered
