from pathlib import Path

import pandas as pd
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter


def _autosize_columns(writer: pd.ExcelWriter, sheet_name: str) -> None:
    worksheet = writer.sheets[sheet_name]
    for column_cells in worksheet.columns:
        max_length = 0
        column_letter = get_column_letter(column_cells[0].column)
        for cell in column_cells:
            if cell.value is not None:
                max_length = max(max_length, len(str(cell.value)))
        worksheet.column_dimensions[column_letter].width = min(max(max_length + 2, 12), 48)


def _style_header(writer: pd.ExcelWriter, sheet_name: str) -> None:
    worksheet = writer.sheets[sheet_name]
    fill = PatternFill(fill_type="solid", fgColor="D9EAF7")
    for cell in worksheet[1]:
        cell.font = Font(bold=True)
        cell.fill = fill


def export_sessions_to_excel(
    sessions_df: pd.DataFrame,
    clashes_df: pd.DataFrame,
    output_path: str | Path,
) -> Path:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    lecturer_name = sessions_df["lecturer_name"].iloc[0] if not sessions_df.empty else ""
    staff_number = sessions_df["staff_number"].iloc[0] if not sessions_df.empty else ""
    month_year = ""
    if not sessions_df.empty:
        first_date = pd.to_datetime(sessions_df["session_date"]).min()
        month_year = first_date.strftime("%B %Y")

    summary_df = pd.DataFrame(
        [
            ("Lecturer name", lecturer_name),
            ("Staff number", staff_number),
            ("Month and year", month_year),
            ("Total sessions", int(len(sessions_df))),
            ("Total hours", float(sessions_df["hours"].sum()) if not sessions_df.empty else 0),
            ("Total amount", float(sessions_df["amount"].sum()) if not sessions_df.empty else 0),
            ("Number of clashes", int(len(clashes_df))),
            ("Number of excluded dates", sessions_df.attrs.get("excluded_dates_count", "")),
            ("Notes", "Generated by Phase 1 backend prototype"),
        ],
        columns=["Metric", "Value"],
    )

    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        sessions_df.to_excel(writer, sheet_name="Generated Sessions", index=False)
        clashes_df.to_excel(writer, sheet_name="Clashes", index=False)
        summary_df.to_excel(writer, sheet_name="Summary", index=False)

        for sheet_name in ("Generated Sessions", "Clashes", "Summary"):
            _style_header(writer, sheet_name)
            _autosize_columns(writer, sheet_name)

    return output
