from __future__ import annotations


TABLE_ORDER = [
    "lecturers",
    "courses",
    "student_groups",
    "timetable_entries",
    "academic_calendar",
    "students",
    "group_enrolments",
    "user_accounts",
    "audit_logs",
]

REVERSE_TABLE_ORDER = list(reversed(TABLE_ORDER))


POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS lecturers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_number TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    full_name TEXT NOT NULL,
    highest_qualification TEXT NOT NULL,
    id_or_passport_number TEXT NOT NULL,
    paye_number TEXT NOT NULL,
    physical_address TEXT NOT NULL,
    contact_number TEXT NOT NULL,
    tariff_per_hour DOUBLE PRECISION NOT NULL CHECK (tariff_per_hour >= 0),
    campus TEXT NOT NULL,
    contract_start_date TEXT NOT NULL,
    contract_end_date TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code TEXT NOT NULL UNIQUE,
    course_name TEXT NOT NULL,
    faculty TEXT NOT NULL,
    department TEXT NOT NULL,
    budget_allocation TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS student_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name TEXT NOT NULL,
    course_id INTEGER NOT NULL REFERENCES courses(id),
    lecturer_id INTEGER REFERENCES lecturers(id),
    campus TEXT NOT NULL,
    study_mode TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS timetable_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id INTEGER NOT NULL REFERENCES lecturers(id),
    group_id INTEGER NOT NULL REFERENCES student_groups(id),
    day_of_week TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    effective_start_date TEXT NOT NULL,
    effective_end_date TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS academic_calendar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    calendar_type TEXT NOT NULL,
    action TEXT NOT NULL,
    allow_override INTEGER NOT NULL DEFAULT 0,
    start_time TEXT,
    end_time TEXT,
    scope_type TEXT NOT NULL DEFAULT 'all',
    lecturer_id INTEGER REFERENCES lecturers(id),
    course_id INTEGER REFERENCES courses(id),
    group_id INTEGER REFERENCES student_groups(id),
    exclude_from_claims_and_registers INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_number TEXT NOT NULL UNIQUE,
    surname TEXT,
    initials TEXT,
    full_name TEXT,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS group_enrolments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    group_id INTEGER NOT NULL REFERENCES student_groups(id),
    active INTEGER NOT NULL DEFAULT 1,
    UNIQUE (student_id, group_id)
);

CREATE TABLE IF NOT EXISTS user_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'lecturer')),
    lecturer_id INTEGER REFERENCES lecturers(id),
    must_change_password INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_login_at TEXT
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id INTEGER REFERENCES user_accounts(id),
    username TEXT,
    role TEXT,
    action TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    details_json TEXT,
    ip_address TEXT,
    success INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_student_groups_lecturer_id ON student_groups(lecturer_id);
CREATE INDEX IF NOT EXISTS idx_timetable_entries_lecturer_id ON timetable_entries(lecturer_id);
CREATE INDEX IF NOT EXISTS idx_timetable_entries_group_id ON timetable_entries(group_id);
CREATE INDEX IF NOT EXISTS idx_group_enrolments_group_id ON group_enrolments(group_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_username ON audit_logs(username);
"""


def postgres_schema_sql() -> str:
    return POSTGRES_SCHEMA_SQL


def assert_postgres_schema_is_not_sqlite_specific() -> None:
    lowered = POSTGRES_SCHEMA_SQL.lower()
    forbidden = ["autoincrement", "sqlite_master", "pragma"]
    found = [token for token in forbidden if token in lowered]
    if found:
        raise AssertionError(f"PostgreSQL schema contains SQLite-specific token(s): {', '.join(found)}")
