from datetime import date, datetime
from copy import copy
from pathlib import Path

import pandas as pd

from app.db_provider import convert_placeholders, get_runtime_connection, rows_to_dicts
from app.docx_utils import ensure_parent, format_month_year
from app.session_generator import dates_between, month_bounds


CHECK_ITEMS = [
    "Claimant signature present",
    "Claimant signature date present",
    "Lecturer signature present on each register page",
    "Staff number present on each register page",
    "Lecturer date present on each register page",
    "Student signatures visible",
    "No manual alteration without approval",
    "All generated register pages submitted",
    "Claim total hours matches generated sessions",
    "Claim total amount matches generated sessions",
]


def get_excluded_date_details(year: int, month: int) -> pd.DataFrame:
    month_start, month_end = month_bounds(year, month)
    rows = []
    for current_date in dates_between(month_start, month_end):
        if current_date.weekday() == 6:
            rows.append({"date": current_date.isoformat(), "reason": "Sunday", "source": "system_default"})

    with get_runtime_connection() as conn:
        calendar_rows = conn.execute(
            convert_placeholders("""
            SELECT title, start_date, end_date, calendar_type
            FROM academic_calendar
            WHERE lower(action) = 'exclude'
              AND date(start_date) <= date(?)
              AND date(end_date) >= date(?)
            """),
            (month_end.isoformat(), month_start.isoformat()),
        ).fetchall()

    for row in rows_to_dicts(calendar_rows):
        start = max(date.fromisoformat(row["start_date"]), month_start)
        end = min(date.fromisoformat(row["end_date"]), month_end)
        for current_date in dates_between(start, end):
            rows.append(
                {
                    "date": current_date.isoformat(),
                    "reason": f"{row['title']} ({row['calendar_type']})",
                    "source": "academic_calendar",
                }
            )
    return pd.DataFrame(rows, columns=["date", "reason", "source"]).drop_duplicates(ignore_index=True)


def generate_verification_checklist(
    sessions_df: pd.DataFrame,
    clashes_df: pd.DataFrame,
    output_path: str | Path,
    year: int,
    month: int,
    documents_generated: bool,
    generation_status: str | None = None,
    notes: str = "",
) -> Path:
    output = ensure_parent(output_path)
    excluded_dates_df = get_excluded_date_details(year, month)
    if sessions_df.empty:
        lecturer_name = ""
        staff_number = ""
        campus = ""
        total_groups = 0
        total_hours = 0
        total_amount = 0
    else:
        lecturer_name = sessions_df["lecturer_name"].iloc[0]
        staff_number = sessions_df["staff_number"].iloc[0]
        campus = sessions_df["campus"].iloc[0]
        total_groups = sessions_df[["course_code", "group_name"]].drop_duplicates().shape[0]
        total_hours = float(sessions_df["hours"].sum())
        total_amount = float(sessions_df["amount"].sum())
    if generation_status is None:
        generation_status = "Generated" if documents_generated else "Blocked due to clashes"

    summary_df = pd.DataFrame(
        [
            ["Generated by system", "pt_claims_system"],
            ["Generated timestamp", datetime.now().replace(microsecond=0).isoformat(sep=" ")],
            ["Lecturer name", lecturer_name],
            ["Staff number", staff_number],
            ["Campus", campus],
            ["Month and year", format_month_year(year, month)],
            ["Total generated sessions", len(sessions_df)],
            ["Total groups", total_groups],
            ["Total hours", round(total_hours, 2)],
            ["Total amount", round(total_amount, 2)],
            ["Number of excluded dates", len(excluded_dates_df)],
            ["Number of clashes", len(clashes_df)],
            ["Documents generated", "Yes" if documents_generated else "No"],
            ["Generation status", generation_status],
            ["Notes", notes],
        ],
        columns=["Metric", "Value"],
    )
    clashes_sheet = clashes_df.copy()
    if clashes_sheet.empty:
        clashes_sheet = pd.DataFrame([{"message": "No clashes detected"}])
    checklist_df = pd.DataFrame(
        [
            {
                "check_item": item,
                "required": "Yes",
                "status": "",
                "reviewer_notes": "",
                "evidence_or_page_reference": "",
            }
            for item in CHECK_ITEMS
        ]
    )

    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        summary_df.to_excel(writer, sheet_name="Summary", index=False)
        sessions_df.to_excel(writer, sheet_name="Generated Sessions", index=False)
        clashes_sheet.to_excel(writer, sheet_name="Clashes", index=False)
        excluded_dates_df.to_excel(writer, sheet_name="Excluded Dates", index=False)
        checklist_df.to_excel(writer, sheet_name="Document Checklist", index=False)
        for sheet_name, worksheet in writer.sheets.items():
            for cell in worksheet[1]:
                font = copy(cell.font)
                font.bold = True
                cell.font = font
            for column_cells in worksheet.columns:
                max_length = max(len(str(cell.value)) if cell.value is not None else 0 for cell in column_cells)
                worksheet.column_dimensions[column_cells[0].column_letter].width = min(max(max_length + 2, 12), 48)
    return output
